### ISSUE TITLE
Key bindings/Hotkeys

### ISSUE THREAD

**Issue by bmburhan22** [cthing/meazure#15]
Someone please add a key binding option for the lines and angles tools. So that on pressing a key say "q" we can set the points of the line segment. "W" to set other 2nd point. E to set 3rd point. When a shortcut key is pressed wherever the mouse pointer is, a point is place.

**Comment by baron1405** [comment]
Changed hotkeys to Ctrl+Shift+n so that Ctrl+n can be used for other purposes.
