### ISSUE TITLE
V3.0: 'Load positions' throws error 'positionLog is not recognized'

### ISSUE THREAD

**Issue by ungeahnt** [cthing/meazure#18]
Thanks a lot for the new version!

But I get the following error when I try to load a position (.mpl) saved with V2.0.1. The position-file works fine with V2.0.1.

btw: with V3 it's not possible for me to create/save positions (the menu is grayed out).

![grafik](https://user-images.githubusercontent.com/28572767/162151591-6ba693b2-380c-474c-8cc2-b52d2866b782.png)

Here the first lines from the mpl:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE positionLog SYSTEM "http://www.cthing.com/dtd/PositionLog1.dtd">
<positionLog version="1">
    <info>
        <title>Meazure Position Log File</title>
        <created date="2022-04-07T07:52:53Z"/>
        <generator name="Meazure" version="2.0.1" build="5"/>
```

**Comment by baron1405** [comment]
The URL for the DTD changed and it appears that the code is not handling redirects. I will implement a fix but for the meantime, the workaround is to edit the position log file and change the DOCTYPE line (line 2) from:
```
<!DOCTYPE positionLog SYSTEM "http://www.cthing.com/dtd/PositionLog1.dtd">
```
to
```
<!DOCTYPE positionLog SYSTEM "https://www.cthing.com/dtd/PositionLog1.dtd">
```
In other words change `http` to `https` in the DTD URL.

**Comment by baron1405** [comment]
Thanks @ungeahnt for reporting the problem! It was a problem with parsing the old URL. Please install the 3.0.1 release to pick up the bug fix.

**Comment by ungeahnt** [comment]
Thanks for the fix. It works now.
