### ISSUE TITLE
[Feature request] Parameter to change the color display format

### ISSUE THREAD

**Issue by Randalf-gh** [cthing/meazure#19]
Pixel color is currently displayed as RGB values, separated with a spece.
Is it possible to add a parameter to have other displays?
In my case I would be interested by having this in hexadecimal, without space. Eg. #8aba82.

Thank you !

**Comment by baron1405** [comment]
Meazure is already able to show the color in a number of different formats including the hex format you are requesting. On the Meazure app go to the **View > Color Format** menu and select the format (e.g. **#RRGGBB**).

**Comment by Randalf-gh** [comment]
Thank you very much, I had not seen this option.
