### ISSUE TITLE
Ability to show supplemental angle

### ISSUE THREAD

**Issue by baron1405** [cthing/meazure#23]
Requested by @linhaiqd:

> One more suggestion is whether the angle value can be increased (180 - angle = angle value). Thank you very much for the software you developed, it helped me a lot.

**Comment by baron1405** [comment]
@linhaiqd can you clarify that you want to be able to change the angle to the supplemental angle.

![GitHub23](https://user-images.githubusercontent.com/989635/164942953-b45438c0-f45a-4aed-ac17-ab1e2e100f64.png)

Currently, Meazure displays angle A in the diagram and you are requesting supplemental angle B. Is that correct? Would you mind describing your use case?

**Comment by linhaiqd** [comment]
> 



> 

Thanks for your reply, yes I meant to increase the value of the supplementary angle B .. Since many angles are measured, increasing the supplementary angle value can improve efficiency.

**Comment by baron1405** [comment]
@linhaiqd could you clarify what you mean by "increase"? I am assuming you want a menu item which will change the display of the angle on the user interface from the value of angle "A" to the value of angle "B" (i.e. the supplemental angle). Is that correct?

**Comment by linhaiqd** [comment]
> @linhaiqd could you clarify what you mean by "increase"? I am assuming you want a menu item which will change the display of the angle on the user interface from the value of angle "A" to the value of angle "B" (i.e. the supplemental angle). Is that correct?

Sorry for my bad English and didn't explain clearly. what I mean is that you can display both the A and B angle values ​​in the angle tool information window, or add an option to display the A or B angle in the menu settings. Both methods are fine. I think it would be better to show both the A and B angles in the tool info window.

**Comment by baron1405** [comment]
@linhaiqd Thanks for the quick reply and clarification!

**Comment by baron1405** [comment]
@linhaiqd Meazure 4.0.0 has been released which provide a `View > Supplemental Angle` menu item to display the supplemental instead of the included angle.
