### ISSUE TITLE
Win 11 - 4K Monitor not detected

### ISSUE THREAD

**Issue by thradde** [cthing/meazure#34]
On Win 11 x64 Meazure reports a screen resolution of 2560 x 1440, but in fact I have a 4K monitor (3840 x 2160).

**Comment by baron1405** [comment]
Thanks @thradde for the bug report. My initial investigation points to Meazure not being DPI aware as described in https://mariusbancila.ro/blog/2021/05/19/how-to-build-high-dpi-aware-native-desktop-applications/. When Meazure was first created, there were no DPI aware APIs. When I created Meazure 3.0, I was not aware of these new APIs so the bug persisted (I do not have a 4K monitor). This bug might also explain an issue people have reported when using screen scaling. I will endeavor to get a fix into the next release of Meazure.

**Comment by thradde** [comment]
I'll be glad to test beta versions for you on my 4K monitor.

**Comment by baron1405** [comment]
@thradde I have started looking into this and have created a VM running Windows with a virtual 4K display. Meazure is showing the correct screen size. I have read that in some cases Windows automatically sets 150% screen scaling when a 4K resolution is set. I have verified that with 150% scaling, Meazure reports 2560 x 1440 for the screen size, which is exactly what you are seeing. Can you verify that your Display settings show 150% scaling and let me know. Thanks.

**Comment by thradde** [comment]
Replied by e-mail, but didn't work. So here is my answer again: yes, I have 150% scaling for the screen.

**Comment by baron1405** [comment]
Excellent, thanks @thradde! I will have support for high DPI monitors in the next release of Meazure. In the meantime you can try the workaround in the second item of the Known Issues section of the README.

**Comment by baron1405** [comment]
This has been fixed and will be in the 4.0 release of Meazure.

**Comment by baron1405** [comment]
Meazure 4.0.0 has been released.
