### ISSUE TITLE
Windows 7 compatibility

### ISSUE THREAD

**Issue by sergeevabc** [cthing/meazure#52]
Dear @cthing, is there any feature in Meazure 4.0 that requires an OS newer than Windows 7 x64? If it's just a matter of compiler flags, then add compatibility, please.

![2024-0314-1521 meazure4 windows7 error](https://github.com/cthing/meazure/assets/373718/8449dd19-3be3-4f9c-89b3-3cf971268550)

Fortunately, Meazure 3.0.2 still works fine and fast.

**Comment by baron1405** [comment]
Unfortunately, we do not have the resources to test and maintain the latest version of Meazure on older versions of Windows. The minimum version for Meazure 4.0 is Windows 10. Given that Windows 7 reached its end-of-life 4 years ago, I suggest upgrading to Windows 10 or 11.

**Comment by sergeevabc** [comment]
Windows 7 is a well-honed OS and does not need support, it is not a car that needs to be refueled from time to time. Moreover, it has all the functions necessary for the operation of Meazure. It's just that the developer forcibly insists on using functions exclusive to Windows 10+. But it makes much more sense when a program serves more people rather than fewer. Specifically, [there is a fix][1] for `GetSystemMetricsForDpi` issue.

[1]: https://github.com/bitsdojo/bitsdojo_window/issues/53#issuecomment-818414974
