### ISSUE TITLE
SecureAge antivirus on VirusTotal flagged the file meazr400x64.exe as Malicious

### ISSUE THREAD

**Issue by Aldo-aldo** [cthing/meazure#53]
Analyzing the folder downloaded from Github with Virustotal, an antivirus flagged the file meazr400x64.exe as Malicious
https://www.virustotal.com/gui/file/4478cca366237ce65e0f2805a74e9f2919f87e87b0a58ed999dee0367cfc8acf
![image](https://github.com/user-attachments/assets/cbd862e0-4c31-4362-b1ed-659ab2eac09a)
the version i installed in 2021 does not have this problem

**Comment by baron1405** [comment]
Scans I have run show that the app package does not have any varus.
