### ISSUE TITLE
Zoom does not fit to cursor

### ISSUE THREAD

**Issue by baron1405** [cthing/meazure#7]
There is a problem with fitting the zoom window and the cursor. Both are at different places - see the picture. The more far the cursor is from the zero point the more difference is there.

![3193847555-Screenshot_1](https://user-images.githubusercontent.com/989635/73596433-f60da180-44d6-11ea-8aae-7ed1653a441f.png)

Possible problem maker: Scale and Layout settings in Windows 10

![2332325702-Screenshot_2](https://user-images.githubusercontent.com/989635/73596455-1178ac80-44d7-11ea-8b79-ffc725a44aa0.png)

**Comment by t-ja** [comment]
I had the same problem with that 125% setting in Windows 8.1. Also, the diplaced screen resolution was wrong. With 100% your tool worked perfect fine, and the correct resolution was displayed. Then, after switching back to 125%, it still worked.

**Comment by baron1405** [comment]
Duplicate of #9, which has a workaround that is now documented in the README file.

**Comment by baron1405** [comment]
Work is being done on Meazure to accommodate high DPI displays with the need for a workaround (#34). The fix will be in the next release of Meazure.
