### ISSUE TITLE
Not correct when scaling screen

### ISSUE THREAD

**Issue by baron1405** [cthing/meazure#9]
I have set Windows to scale text, apps, and other items to 125%, and then Meazure doesn't display the correct information from the location of the pointer. Assume that Meazure does not pick up the scaling - and is therefore not very useful to me. Is it possible to fix this?

![screenshot](https://user-images.githubusercontent.com/989635/73596502-5b619280-44d7-11ea-9728-fa94aefea266.png)

**Comment by baron1405** [comment]
Sorry this posting is six months later, but, yes, I am a user who has found a fix for Windows 10, even though the Meazure developers apparently won’t or can’t fix this. Other color tools have the same problem, which is due to Microsoft (of course) changing how screen addressing works.

I experimented with the Compatibility settings in the Properties context (right menu button) menu for the Meazure icon.

What worked is Compatibility > Change high DPI settings button > Override high DPI scaling behavior Scaling performed by: Application checkbox.

I hope this information can get out to users, because Meazure really seems to be the best measurement/color tool. It is so useful to have it fixed and working again!

**Comment by Obiwan-Kennedy** [comment]
Hello baron105,
Many thanks for this workaround !
Works also fine on my computer.
Regards

**Comment by baron1405** [comment]
Meazure 4.0.0 has been released, which supports high DPI monitors and display scaling. Please undo the workaround and try to new release.
